[package]
name = "number_of_nodes_in_the_sub_tree_with_the_same_label"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
