[package]
name = "remove_zero_sum_consecutive_nodes_from_linked_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
