[package]
name = "decode_the_morse_code"
version = "0.1.0"
authors = ["Alexandru Olaru <alxolr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
